### ISSUE TITLE
First line of some forms are being clipped

### ISSUE THREAD

**Issue by dncnkrs** [gregstein/DE-Replays-Manager#2]
Hi Greg

On a couple of the pages I'm seeing the first lines of the forms being clipped a little. I'm seeing this on the 'Browse Replays' and 'Search Players' tab.

If you can't repro let me know, I can probably fix it, it's just been a while since I've played with winforms.

![image](https://user-images.githubusercontent.com/15052417/123548501-e2627b00-d75c-11eb-8b9c-79ee370ebd3d.png)

![image](https://user-images.githubusercontent.com/15052417/123548487-d7a7e600-d75c-11eb-9fce-be97940b9017.png)

**Comment by gregstein** [comment]
Holly freaking molly! Thanks for reporting!! And feel free to contribute. I will take a look at it too later as im busy with work lately.
