### ISSUE TITLE
Replay Manager captures `delete` keypress when open

### ISSUE THREAD

**Issue by KSneijders** [gregstein/DE-Replays-Manager#7]
Hi,

### Short thank you (bug report below)

First of all, thanks for this amazing tool! 
I've been using it to try and validate the structure of scenario files for older versions for [my library](https://github.com/KSneijders/AoE2ScenarioParser). 
And without this tool, that'd have basically been impossible.

### Report

Whenever I have the program open, I cannot use `delete` anywhere on my computer (in text editors, macros etc.) as soon as I close the program, it works again. Not a huge hassle, but I assume a bug 🙂

**Comment by gregstein** [comment]
Hello @KSneijders,
Fixed in release 1.6.

Thank you for reporting!
